### ISSUE TITLE
Wondering who owns/maintains this project now

### ISSUE THREAD

**Issue by LappleApple** [zalando/db_agg#17]
Please advise -- thanks!

**Comment by hjacobs** [comment]
I think @arbru is the original developer.

**Comment by LappleApple** [comment]
Thank you, @hjacobs. @arbru, wondering if you've got plans to develop this project further, if you'd like to hand it off to someone else, or "other." We have [this new org](https://github.com/zalando-incubator) for dormant projects to remain public and could move it there, if you're open to that.

**Comment by arbru** [comment]
yes, there are plans for further development from my side.
in fact there are much new features which are still in a very experimental state 
which i hope to commit soon as soon as they are more matured.

**Comment by LappleApple** [comment]
Thanks, @arbru. Do you have an estimated timeline on the features? And is it possible to find you additional contributors to help make this project work go faster?
